export default {
	"Theme-version"					:"",
	"Cdn-version"					:"",
	"backup-datastore"				: false,
	"turnoff-audio-ingame"			: true,
	"Change-CDN-version"			: false,
	"Elaina-Plugins"				: true,
	"Banner-list": [
					"1_winter-noble_2023.png",
					"2_winter-royal_2023.png",
					"3_winter-aurora_2023.png",
					"bee2023.png",
					"challenger.png",
					"lny2023.png",
					"soul-fighters_2023.png", 
					"faker_1.png", 
					"faker_2.png",
					"arcane_fractured-jinx.png",
					"noxus.png",
	],
	"Font-list"	: [
					"aegirseaborn.ttf",
					"elaina-herculanum_roman.ttf",
					"minecraftregular-bmg3.otf",
					"roboto-medium.ttf"
	],
	"CurrentBanner"					: "faker_2.png",
  	"old-prev/next-button"			: false,
  	'pause-audio'					: 1,
  	'pause-wallpaper'				: 1,
	'mute-audio'					: false,
	"NextBg_Count"					: 0,
  	"wallpaper-volume"				: 0.0,
  	"audio-volume"					: 0.15,
  	"audio-loop"					: false,
  	"Receive-Update"				: true,
  	"Continues_Audio"				: true,
  	"sidebar-transparent"			: false,
  	"hide-champions-splash-art"		: false,
  	"Custom-Font"					: true,
  	"Custom_RP"						: false,
  	"RP-data"						: "-69",
  	"Custom_BE"						: false,
  	"BE"							: "-69",
  	"Custom-Rank-Name"				: true,
  	"Rank-line1"					: "Apprentice",
  	"Rank-line2"					: "Witch",
  	"animate-loading"				: false,
  	"Custom-Avatar"					: true,
  	"Custom-Icon"					: true,
  	"Custom-Cursor"					: false,
  	"settings-dialogs-transparent"	: false,
  	"Hide-linking-settings"			: true,
  	"Hide-verify-acc"				: true,
  	"new-gamesearch-queue"			: true,
  	"hide-vertical-lines"			: true,
  	"auto_accept"					: false,
  	"aram-only"						: false,
  	"Old-League-Loader-Settings"	: true,
  	"Auto-Find-Queue"				: false,
  	"Create-Delay"					: 15000,
  	"Find-Delay"					: 10000,
  	"Gamemode"						: 450,
  	"Ranked Queue ID"				: 2,
  	"Ranked Tier ID"				: 9,
  	"Ranked Division ID"			: 0,
  	"Custom-Status"					: false,
  	"status-delay"					: 10000,
  	"Merry-Christmas"				: true,
  	"April fool` joke"				: false,
  	"loot-helper"					: true,
  	"ChampsPrice"					: 450,
  	"buy-all-champs"				: true,
  	"Name-Spoofer"					: false,
  	"Spoof-name"					: "Elaina Da Catto",
  	"Dev-mode"						: false,
  	"Custom-rank"					: true,
  	"Runes-BG"						: true,
  	"hide-overview"					: true,
  	"hide-merch"					: true,
  	"hide-patch-note"				: true,
  	"hide-esport"					: true,
  	"Custom-Border"					: true,
  	"Custom-RP-Icon"				: true,
  	"Custom-BE-Icon"				: true,
  	"Custom-Rank-Icon"				: true,
  	"Custom-Emblem"					: true,
  	"Custom-Clash-banner"			: true,
  	"Custom-Ticker"					: true,
  	"Custom-Trophy"					: true,
  	"Custom-Regalia-Banner"			: true,
  	"Custom-Hover-card-backdrop"	: true,
	"Custom-Gamemode-Icon"			: true,
  	"Debug-mode"					: false,
  	"Custom-profile-hover"			: false,
  	"Custom-mastery-score"			: true,
  	"Custom-challenge-crystal"		: true,
  	"Mastery-Score"					: 6969,
  	"Challenge-Points"				: 6969,
  	"challengeCrystalLevel"			: 9,
  	"Active-dev-button"				: 0,
  	"hide-theme-usage-time"			: false,
  	"auto_accept_button"			: true,
  	"Force-Update"					: false,
  	"CurrentFont"					: "elaina-herculanum_roman.ttf",
  	"prevent-manual-update"			: false,
  	"NSFW-Content"					: false,
  	"Enable-Invite-Fr"				: true,
  	"Auto-Honor"					: true,
	"Dev-button"					: false,
	"Elaina-First run"				: false,
	"seconds1"						: 0,
	"minutes1"						: 0,
	"hours1"						: 0,
	"custom-navbar-css"				: true,
	"manual-wallpaper-name"			: "Ex: Wallpaper.webm",
	"manual-audio-name"				: "Ex: Audio.mp3",
	"manual-banner-name"			: "Ex: Banner.png",
	"manual-font-name"				: "Ex: Font.ttf",
	"change-nickname-color"			: true,
	"nickname-color"				: "#f2c1d0",
	"nickname-opacity"				: "ff",
	"nickname-color-with-opacity"	: "#f2c1d0ff",
	"lobby-transparent-filter"		: true,
	"Disable-Theme-Audio"			: false,
	"hide-tft-home"					: false,
	"hide-tft-battle-pass"			: false,
	"hide-tft-troves"				: false,
	"hide-tft-rotational-shop"		: false,
	"hide-tft-news"					: false,
	"hide-tft-match-history"		: false,
	"wallpaper-slideshow"			: false,
	"wallpaper-change-slide-time"	: 10000,
	"navbar-content"				: [],
	"enable-hide-top-navbar-friendlist-button": true,
	"System-Info"					: "",
	"last-backup-time"				: "",
	"custom-champs-image"			: false,	
	"dodge-button"					: true,
	"holiday-message"				: true,
}