let dateObj = new Date();
let month = dateObj.getUTCMonth() + 1;
let day = dateObj.getUTCDate();
let newdate = day + "/" + month

if (newdate == "25/12" && DataStore.get("Merry-Christmas")){
    console.log('                                                                               .:!!!!77!!:                              ')
    console.log('                                                                           .^!?5PPPPPPPPPPY~.                           ')
    console.log('                                                                    .::^!?Y5PPPPPPPPPPPPPPPGPJ~.                        ')
    console.log('                                                               .:^~Y57~!J5GGPPPPPPPPPPPPPPPPPPGPJ!^^::..                ')
    console.log('                                                           .^75PPGGPPP5?^:~?PGPPPPPPPPPPPPPPPPPPPGGPPPPP5J.             ')
    console.log('                                                       ::~JPGGPPPPPPPPPPPY!::75PPPPPPPPPPPPPPPPPPPPGPY7JP!              ')
    console.log('                                                     ~7~^~!7?JY5PPPPPPPPPPP5?^:!YPPPPPPPPPPPPPGGPYJ7:  .^               ')
    console.log('                                                  .5G5YJ?7!~^^^^^~!?JY5PPPPGPJ~:~YPPPPPPPPPPY?~.       ^.               ')
    console.log('                                  .:^^^^~^.      :7PGPPPPPPPPP55YJ?7!^^^^~7JYPGPY~:~YPPPPPPPP?       :~77!~^.           ')
    console.log('                             .^7J5PPGGGGGGPY~  :YGGPPPPPPPPPPPPPPPPPPP5YJ7!~^^~7J5J~:!5GPPPGB7     :??7!~~~~7!          ')
    console.log('                          .~JPGGPPPPPPPPPPPGGPYBGPPPPPPPPPPPPPPPPPPPPPPPPPPPPYJ7~~~~^::?PGPPGJ    .J?~^^~~~^7?!         ')
    console.log('                        :?PGGPPPPPPPPPPPPGGBBB#GGGGGGGGGGGPPPPPPPGGGGGGPPPPPPPPPPP5J7~^:~J5PP~    .J~^^^^^^~J7!         ')
    console.log('                      .JGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGPP5?!^?5      :7!7!!!7??!          ')
    console.log('                      7#PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGPPPG5YJ7~^. :~!77!^.           ')
    console.log('                       ?GGPPPGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP555PPPPPPPPPP5Y7^.                ')
    console.log('                        ^5GGPPGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP55555YYYYYYYYYYYYYYYYYY5555J!:             ')
    console.log('                          ^YGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGBBPP5555YYYYYYYYYY555YYYYYYYYYYYYJJJJYJ7~.          ')
    console.log('                            :75GGPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGGP5YJ?7!~~~^^^^^^^^^^^~~!?YP5YJJJJJJ??????????!~.        ')
    console.log('                               ^?5GGGPPPPPPPPPPPPPPPPPPGPP55YJ?7!~::::::::::::::::::::....^7Y5YJ??777777777!!7J~        ')
    console.log('                                  :!YBPPPPPPPP55YYJJJ???77!!~^^7:7:::::::::::::~:::::::^:::.:!55YYJ7!!!!!!!7?7:         ')
    console.log('                                    ??!77777777!!!!!!~~~^^:::.:Y^!:::::::::::^.J~.:^::~Y~.::^^~P5YJ7!77777!^.           ')
    console.log('                                   ?7.::^^^^^^^::::::^::::::.^7~?~^:::::::::~:~J7!:^7^!GJ.::::^^GY?77J?^:.              ')
    console.log('                                  ^J.::::::::::::::::7:::...^~..!J!.::::::::^^J:.~7:7~~Y~::::::^J?^^^^.                 ')
    console.log('                                  Y^::::::::::::::::~7..^!755JJ7~?G^.::::::^^J^.^!JPYPJ5:::::^~:?7                      ')
    console.log('                                 ^J.:::::::::::::::.!!:5BPG#####57?J~:::::^~5^^!G###GGJP?:::::~^~J.                     ')
    console.log('                                 ?!.::::^^:::::::::.?J??!PBGGBB?~~.:~7^.::::Y:.7BGGGBY!:^:::::^7.Y:                     ')
    console.log('                                 Y^:::::~7^::::::::.Y7..!BGGGGGGGG:..:!7^.:.Y^.PBGGGGPB~^:::.^J! Y.                     ')
    console.log('                                :Y.::::.!?!::::::::.Y~..?BPP55555P^....^7!^.J^.PGPPPP5G7..::!57Y!7                      ')
    console.log('                                ~?.::::.77^7.::::!:.?!..^5YYJJJJJ5:......:~!J^.?5JJJJJB!^~~7?!.?J.                      ')
    console.log('                                ?!.:::::?:^PJ.:::^!.~7...:JJJJJYY~.............:?YJJYYJ?!!::^^:~7                       ')
    console.log('                                Y::::.:7~~7~#J:.:.^!:?....^7???!:...^^^^^^^^^^^..!??7:.:~:::~~^:J                       ')
    console.log('                               ^J...:~7!!!.^5~7~:..~YJ~...........:?7!!!!777!!J~.....::^^:::^!^.7^                      ')
    console.log('                               J!^~7?7!~:..!J.:~7!^.?G!...........J!^~~~~~~~^^J^.....~:~:::.~!::^^                      ')
    console.log('                              :J:^^^^?:.:.^5~.:.:~5Y~JJ:..........?!^^^^^^^~!?!:^!~~J~^^:::.7!::::                      ')
    console.log('                              J~.:::.7~.^7YY.:::.^#JJ5GJ??7!!~~~~!7YY??JJYY5PJ?J?5?.J~!!:::~J::::.                      ')
    console.log('                             ~?.::::~^:.7JJ^:::::JGP?!~~~~~!!!!!!BBGB&BGGB7!7??!!75^~J!~^::!:.:~:                       ')
    console.log('                            .Y:::::.!^::?J~.::::JJPP!~~~~~~~~~~!?JY5PPGP55?~^~JJ7!?J.7BYJ?PY??P~                        ')
    console.log('                            J~.::::^!^^??~.::.:?J!~7J!~~~~~~~~Y5!^~~~Y5~^~75?~~!7?75^^&!.:J?!J?                         ')
    console.log('                           ?~.:::::!:.^?^.::.^YY!~~^~~~~~~~~~~!Y7~~~!YY!7~!5Y~~~~~?P!75.:.77~7!.                        ')
    console.log('                     ..::^J7^^^^^^~~:~!^:::.~Y~~??77~~~^~~~~~~~!Y!~?J5.7GJ?5~~~~~~!B7J^:::!^.^~7:                       ')
    console.log('                .^~!!~~^^::.::::^~!~7J~::.:7?:~::.JBGP5J?7!!~~~~7JJ7?!::!YYPJYY5PGBBY~...7!?:::~.                       ')
    console.log('             :~!!^:.                .:^^~~?!.~^~?5GPGGGGBGGGGBGGG#GPG^::.:YBGGGGGGPPGPY!:57~J^:.                        ')
    console.log('           ^7!:                         .^^^~JYB&#PGGPPPPPPGGB&GGGGG#~ ..  7GPPPGGGGPGGGPY!~?^:                         ')
    console.log('         :?!.                              .?BB#&GGGGGGGGGGGGG#BPPPPBG^.... JBPGGGGGGGGPGB55:~:  .:                     ')
    console.log('        ~?.                                  ~B&&P5J?777777?JYPBGGPGG#J!^..~?GGPGGGGGGGGGPGBJ~!^~7.                     ')
    console.log('       ~J                               ~!^   ^B7^:::::::::::::^7GGGP#PJ7!~JJ5BGGGGGGGGGGGGPGGG7^                       ')
    console.log('      .Y.                                .^!~. 7J.::::::^:^^^^::.7BPPB57!: :!?PGPPPPPPPPGGGGGGBPJJ^                     ')
    console.log('      ~?                                    :7~.P~~~YJY!J7YY!^^~!7#GP#Y^     .!BGGGGGGGGGGGGGGGGPGG7                    ')
    console.log('      7!                                      ~?P~.7PYP?:.^~~!~..:?GGGP?JJJJJJYPPPPPPPPPPPP5555YYYY5Y:                  ')
    console.log('      ^J                                       ~G: !7..~7^    ::   .YPPPPPPPP555555555YYYYYYYYYYYY55PG!.^!7^            ')
    console.log('       J^                                  .^~~75?!^7J!^77!~^:..^7~~J5YYYYYYYYYYYYYYYYYYYY5555PPPP5Y?77^7?!:            ')
    console.log('       .J:                               .!!^.~7. ..^Y:.   .:^~5GPPPP555555555555PPPPPPPPPP5YJ?!^:.  ~:7!^              ')
    console.log('        .?~                               .  !7      ^         JJ???JJJJJJJ5#BBBY??77!!~^:..          ~!:               ')
    console.log('          ~7^                                .               :7!            ?5PB~                         .             ')
    console.log('           .~7!:                                         .^~!~.               .:.                                       ')
    console.log('              :~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!~^.                                                            ')
}